spring:
  application:
    name: Pismo Challenge

  datasource:
    url: jdbc:h2:mem:pismo
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console


